## Edited on 10/2/2025 - 10/5/2025
Tyler Lovison
AI240

## Exercise 1

In [1]:
!pip install numpy


In [2]:
!pip install scikit-learn

In [3]:
!pip show scikit-learn

Name: scikit-learn
Version: 1.5.1
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: C:\Users\tmlov\anaconda3\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: imbalanced-learn


## Exercise 2

In [4]:
import numpy as np
import pandas as pd

import sklearn
from sklearn import datasets


## Exercise 3

In [5]:
iris = datasets.load_iris()

# dataset includes:
# Feature matrix (X)
# Response vector (y)
# Feature names
# Target names


## Exercise 4

In [6]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names

print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])


Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


## Exercise 5

In [7]:
from sklearn.model_selection import train_test_split

# Split data into training (80%) and testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


X_train shape: (120, 4)
X_test shape: (30, 4)
y_train shape: (120,)
y_test shape: (30,)


## Exercise 6

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# Initialize KNN with k = 5
classifier_knn = KNeighborsClassifier(n_neighbors=5)

# Train the model
classifier_knn.fit(X_train, y_train)

# Predict using test data
y_pred = classifier_knn.predict(X_test)

# Evaluate model accuracy
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))


Accuracy: 1.0
