# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

## Exercise 1

In [1]:
!pip install Numpy

## Exercise 2 

In [2]:
import numpy as np

## Exercise 3

In [3]:
data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


## Exercise 4

In [4]:
import numpy as np

arr1d = np.array([10, 20, 30, 40, 50])
print("1-D Array:", arr1d)


1-D Array: [10 20 30 40 50]


In [5]:
arr2d = np.array([[10, 20, 30], [40, 50, 60]])
print("2-D Array:\n", arr2d)


2-D Array:
 [[10 20 30]
 [40 50 60]]


In [6]:
print("First element of arr1d:", arr1d[0])
print("Second row, third column of arr2d:", arr2d[1,2])


First element of arr1d: 10
Second row, third column of arr2d: 60


In [7]:
print("Slice arr1d from index 1 to 3:", arr1d[1:4])
print("Slice arr2d first row:", arr2d[0, :])


Slice arr1d from index 1 to 3: [20 30 40]
Slice arr2d first row: [10 20 30]


In [8]:
num_arr = np.array([30, 20, 40, 10])
print("Sorted numeric array:", np.sort(num_arr))

alpha_arr = np.array(['kiwi', 'berry', 'pear'])
print("Sorted alphabetic array:", np.sort(alpha_arr))


Sorted numeric array: [10 20 30 40]
Sorted alphabetic array: ['berry' 'kiwi' 'pear']


In [9]:
zeros = np.zeros(5)
ones = np.ones(5)
range_arr = np.arange(1, 11)
lin_arr = np.linspace(0, 1, 5)

print("Zeros:", zeros)
print("Ones:", ones)
print("Range:", range_arr)
print("Linspace:", lin_arr)


Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Range: [ 1  2  3  4  5  6  7  8  9 10]
Linspace: [0.   0.25 0.5  0.75 1.  ]


## Exercise 5

In [10]:
import numpy as np

arr = np.array([3, 2, 14, 9, 10, 12])

# Find index where value is 9
indexes = np.where(arr == 9)
print("Indexes of 9:", indexes[0])


Indexes of 9: [3]


## Exercise 6

In [11]:
arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

joined_array = np.concatenate((arr1, arr2))
print("Joined Array:", joined_array)

Joined Array: [ 9  5  8 55 89 76]
